### ISSUE TITLE
Rigctld caps-targetable_vfo

### ISSUE THREAD

**Issue by PianetaRadio** [Hamlib/Hamlib#987] opened 2022-03-18 16:50 UTC
Using Yaesu FT991A that has caps.targetable_vfo = RIG_TARGETABLE_FREQ
If I connect by usig rigctld, this is what I get:

```
2022-03-18:16:41:44.308355: read_string called, rxmax=1024
2022-03-18:16:41:44.308355: read_string(): RX 19 characters
2022-03-18:16:41:44.308355: 0000    74 61 72 67 65 74 61 62 6c 65 5f 76 66 6f 3d 30     targetable_vfo=0
2022-03-18:16:41:44.308355: 0010    78 33 0a                                            x3.             
2022-03-18:16:41:44.308355: netrigctl_open: unknown setting='targetable_vfo=0x3'
```

and the caps.targetable_vfo is recognized as 0

**Comment by PianetaRadio** [comment] 2022-03-18 18:12
For the sake of clarity, I'm using hamlib v 4.4 and 0x3 comes from:

ft991.c
`    .targetable_vfo =     RIG_TARGETABLE_FREQ | RIG_TARGETABLE_MODE,`

So, rigctld get from backend of FT991 the right value of targetable_vfo, but recognize it as an error!

(In the actual master code RIG_TARGETABLE_MODE was removed, because it was not correct for this radio)

**Comment by mdblack98** [comment] 2022-03-18 21:50
Duplicate of https://github.com/Hamlib/Hamlib/issues/732

**Closed by mdblack98** 2022-03-18 21:50 UTC
Labels: duplicate
