### ISSUE TITLE
Error on current hamlib with Xiegu X6100 and truSDX

### ISSUE THREAD

**Issue by dk5cr** [Hamlib/Hamlib#1499] opened 2024-01-31 21:25 UTC
Preparing my holiday ham radio equipment i tried to set up wsjtx 271 (dev) with my truSDX with the current firmware (2.00u and 2.00x as second try) and with my Xiegu X6100, both connected via USB. 
Connection parameters set under Win10 in device-manager from 19200 to max of 115200 or so, parameters for 8,N,1 unchanged to last time, it worked with the same setup, but older WSJTX-version (2.5.4, but no more installed). 

When connection truSDX with truSDX driver-programm every time WSJTX mentions hamlib errors, that connection to the rig is absolutely impossible due to connection timeouts. So enough time wasted with truSDX i tried my Xiegu and also errors occur, which i added as attachement. The main statement is "Feature not available". 
![hamliberror_x6100](https://github.com/Hamlib/Hamlib/assets/149412955/a6927a4a-55a1-41dc-85cf-1d975946aaab)

Trying different settings (as other baud rate) the connection is either "rejected" or "timed out" or "protocol error", especially when changing on the other com port or - new error - getting "feature not available while getting current mode". 

I tried with the current firmware of my xiegu on 4 (!) different windows 10-laptops and desktops and got the same results. 

So where's my fault? What's wrong with the setup? What's eventually wrong with hamlib 4.6 from 2024-01-30? 

HELP... 
Thanks and cheers, 73 Cornel DK5CR

[ADDED:] Just tried to us Xiegu X108G as device and few seconds later "Test CAT"-Button jumped to green with the same settings but the rig. Also PTT worked. BUT: Audio line via USB crashes, cause X6100 loses its audio devices, perhaps due to some CAT-commands. Also works on X5105 with CAT, but PTT doesn't work properly (letting lose PTT occurs an error). 

So it seems to be a specific error-issue for the X6100 in the hamlib library.

**Comment by mdblack98** [comment] 2024-01-31 21:59
Please place this file as described below
https://www.dropbox.com/s/t52ngcalsgnpm8m/wsjtx_log_config.ini?dl=0

	C:\Users\[username]\AppData\Local\WSJT-X
	The WSJT-X_Rigcontrol.log file will be in the same location
	Here's a youtube video showing Windows users howto -- https://www.youtube.com/watch?v=q9tAvhNmSvc

For Linux put it in  
	~/.config
	The WSJT-X_Rigcontrol.log file will be here:
	~/.local/share/WSJT-X

For MacOS put it in
	/Users/[username]/Library/Preferences
 
Restart WSJT-X and duplicate the problem.
Shut down WSJT-X

Then send me the WSJT-X_RigControl.log file
Mike W9MDB

**Comment by dk5cr** [comment] 2024-01-31 22:04
Here is the file as desired: 

[WSJT-X_RigControl.log](https://github.com/Hamlib/Hamlib/files/14117781/WSJT-X_RigControl.log)

**Comment by dk5cr** [comment] 2024-02-16 10:03
Do you have new information concerning this issue?

**Comment by dk5cr** [comment] 2024-03-12 14:31
Hi mdblack98, 
thanks for fixing the issue. But how ccan i test the new dll? Where do i find it? 
Obviously i'm to studid to find the link/place/page where to download and test it. 
Thanx and 73

**Comment by mdblack98** [comment] 2024-03-12 14:39
If running the latest WSJT-X (rc4) there's a Hamlib update in the rig tab.
Otherwise new hamlib for installation directions
#1 Shut down WSJTX 
#2 Download either the 32-bit or 64-bit DLL matching the 32/64-bit version of WSJTX -- hopefully your browser doesn't block it but may warn you multiple times.
If you can do a "Save As" you can save it directly in the appropriate WSJTX directoryC:\WSJT\WSJTX\bin and replace the libhamlib-4.dll that is there.
http://n0nb.users.sourceforge.net/dll32/libhamlib-4.dll
http://n0nb.users.sourceforge.net/dll64/libhamlib-4.dll
Linux/Unix/Mac users need to compile the latest tar file from http://n0nb.users.sourceforge.netNote: If compiling on Unix-like systems please uninstall any Hamlib package you have before installing the new build
#3 If you don't save directly you need to open a file browser and move the file that way.
If you're not familiar with that here's a video on the file browser - https://www.youtube.com/watch?v=AyVqCJrs9dk
Once installed on Linux do "ldconfig".
rigctl --version should then show a relatively recent date of the download
Mike W9MDB


 

    On Tuesday, March 12, 2024 at 09:31:51 AM CDT, dk5cr ***@***.***> wrote:  
 
 


Hi mdblack98,
thanks for fixing the issue. But how ccan i test the new dll? Where do i find it?
Obviously i'm to studid to find the link/place/page where to download and test it.
Thanx and 73

**Comment by dk5cr** [comment] 2024-03-12 14:57
Thank you Mike for the instructions. I downloaded 2.7.0 rc4 (i had installied 2.7.1. dev before, but uninstalled to make sure, that there's no problem with dev-versions). After installing 2.7.0 rc4 i tried to "update hamlib" (32bit), the program tells me: 
"Error loading libhamlib-4.dll
 TLS initialization failed" 

When copying the downloaded libhamlib-4.dll manually to the directory (c:\wsjt\wsjtx\bin) the error still occurs with slightly different values: 

![current_hamlib_error](https://github.com/Hamlib/Hamlib/assets/149412955/41577d98-1b4a-435e-9a30-84dd572e13fb)

**Comment by mdblack98** [comment] 2024-03-12 15:03
From the WSJT-X manual.
   
   -    
You can download a suitable OpenSSL package for Windows from Windows OpenSSL Packages; you need the latest Windows Light version. For the 32-bit WSJT-X build, use the latest Win32 v1.1.1 version of the OpenSSL libraries, for the 64-bit WSJT-X use the latest Win64 v1.1.1 version of the OpenSSL libraries (Note: it is OK to install both versions on a 64-bit system) which, at the time of writing, were Win32 OpenSSL Light Package and Win64 OpenSSL Light Package respectively.

   -    
Install the package and accept the default options, including the option to copy the OpenSSL DLLs to the Windows system directory. There is no obligation to donate to the OpenSSL project. Un-check all the donation options if desired.




 

    On Tuesday, March 12, 2024 at 09:57:32 AM CDT, dk5cr ***@***.***> wrote:  
 
 


Thank you Mike for the instructions. I downloaded 2.7.0 rc4 (i had installied 2.7.1. dev before, but uninstalled to make sure, that there's no problem with dev-versions). After installing 2.7.0 rc4 i tried to "update hamlib" (32bit), the program tells me:
"Error loading libhamlib-4.dll
TLS initialization failed"

When copying the downloaded libhamlib-4.dll manually to the directory (c:\wsjt\wsjtx\bin) the error still occurs with slightly different values:

current_hamlib_error.png (view on web)

**Comment by dk5cr** [comment] 2024-03-12 15:19
Thanks again. What i don't understand is, that everything worked fine with my Xiegu to version 2.5.1. I didn't do an update for firmware or so and everything went fine even without OpenSSL-components installied. But no it doesn't work... 

I'm gonna try to install OpenSSL32, but i'm a little confused, because OpenSSL exists at sourcefourge in version 1.1.1. as mentioned, but download-packages have versions like Win32_OpenSSL_v3.2.1 or so... 

Sometimes i wish, things would be easier and less dependant to lots of other stuff. 
Anyway thanks for you patience. 
73 Cornel, DK5CR

**Comment by mdblack98** [comment] 2024-03-12 16:07
Are you running the 1.7 firmware?  Perhaps need to reload it?
The response to the 0x25 command is completely wrong and is why it's getting the error.


https://xiegu.eu/downloads/


 

    On Tuesday, March 12, 2024 at 10:53:17 AM CDT, dk5cr ***@***.***> wrote:  
 
 


After installing, testing and so on, this error is on top:

new_current_hamlib_error.png (view on web)

**Comment by dk5cr** [comment] 2024-03-12 16:16
Sorry, but that's exact this firmware on my rig like mentioned on xiegu.eu-page: 

![Uploading IMG_20240312_171514_DRO.jpg…]()

**Comment by mdblack98** [comment] 2024-03-12 16:22
Please reload the firmware.Looks like something is corrupted.

 

    On Tuesday, March 12, 2024 at 11:16:53 AM CDT, dk5cr ***@***.***> wrote:  
 
 


Sorry, but that's exact this firmware on my rig like mentioned on xiegu.eu-page:

**Comment by dk5cr** [comment] 2024-03-12 16:29
reload 1.1.7 or the non-experimental 1.1.6?

**Comment by mdblack98** [comment] 2024-03-12 16:32
Try reloading 1.1.7 first -- if it doesn't work try 1.1.6
They either broke 1.1.7 or your installation was corrupted.
Mike W9MDB

 

    On Tuesday, March 12, 2024 at 11:29:43 AM CDT, dk5cr ***@***.***> wrote:  
 
 


reload 1.1.7 or the non-experimental 1.1.6?

**Comment by mdblack98** [comment] 2024-03-12 17:02
I would agree.
Let me do some checking....
Mike W9MDB


 

    On Tuesday, March 12, 2024 at 11:54:10 AM CDT, dk5cr ***@***.***> wrote:  
 
 


Hi Mike,
sorry for bad news, but...
When flashing 1.1.7 again the error is still there. Flashing down to 1.1.6 the error is exact the same as in the screenshot 1hr ago.

It seems a little unlikely to me, that both images should be corrupt.

Cornel DK5CR

**Comment by dk5cr** [comment] 2024-03-18 11:51
Hi Mike, 
did you do some checking? Any results? Any proposals to solve the problem? 
Cheers and 73 
Cornel DK5CR

**Comment by lxe** [comment] 2024-03-18 17:40
I've been having this issue but then upgraded hamlib dll to the latest `hamlib-w64-4.6~git-20240318-1de9a5ced.zip` git snapshot. Now the radio correctly switches frequency, but it's reporting it x1000 back to wsjt:

<img width="394" alt="Screenshot 2024-03-18 103817" src="https://github.com/Hamlib/Hamlib/assets/1486609/975ac745-1564-40c6-8a80-0f1d3af82634">

**Comment by mdblack98** [comment] 2024-03-20 13:57
Download again...you may have downloaded before the new version was uploaded.

You should see this
rigctl-wsjtx.exe --versionrigctl Hamlib 4.6~git 2024-03-19T22:51:03Z SHA=538d41 64-bit
I suspect you got the 2024-03-18 version
Also I have a 6100 here now and I'm seeing one COM port works and the other one doesn't.I have COM6 and COM7 and COM7 works but COM6 does not.
Mike W9MDB
 

    On Wednesday, March 20, 2024 at 03:22:24 AM CDT, dk5cr ***@***.***> wrote:  
 
 


Hi,
with downloading http://n0nb.users.sourceforge.net/dll32/libhamlib-4.dll i couldn't see any change.
So please tell me (for dummies) where to find the fixed dll-file for downloading and testing.
Thx and 73
Cornel DK5CR

**Comment by lxe** [comment] 2024-03-20 18:46
I opened a new ticket for my issue with reproduction steps, as it's either not related or tangentially related to this issue: https://github.com/Hamlib/Hamlib/issues/1527

**Comment by mdblack98** [comment] 2024-03-21 03:50
X6100 working here with APP 1.1.7 Base 1.1.6
Frequency: 14074000

There is a bug in the 1.1.7 version that cannot read VFOB at all with 0x25 (it just returns VFOA all the time).  So Rig Split will not work.  I've submitted a bug report so hopefully that will be fixed in 1.1.8.  Meanwhile the IC-7000 selection works as it does not use the 0x25 command.

**Comment by dk5cr** [comment] 2024-03-21 09:35
> n't.I have COM6 an

Hi, 
x6100 offers two com-ports. One is for transmitting audio, the other one is for CAT-purposes. Rule is to take the com-port with the higher number for CAT. For me, this works with the com-port. Gonna download again and see if error is gone or at least reduced. 
Btw: I've got a 32bit version and hope, the error is also fixed in the 32bit. 

Tnx and 73

**Comment by dk5cr** [comment] 2024-03-21 09:45
Just check out the 32bit version with timestamp 2024-03-19 / 22:51:03Z: 

Error is still the same, Feature not available while getting current frequency... 

:-(

**Comment by dk5cr** [comment] 2024-03-21 12:25
Just tried the whole bunch of ideas on another computer, but when connecting the Xiegu x6100 to the other pc, then the same error in wsjtx 2.7.1.dev and 2.6.1 occured. 
![x6100_wsjtx_error](https://github.com/Hamlib/Hamlib/assets/149412955/ea71b3a5-6b1b-49e4-8e73-72afcc308549)

**Comment by mdblack98** [comment] 2024-03-21 13:12
32-bit works here fine too.  But only at 19,200 baud which seems to be highest baud rate supported by the X6100.

Mike W9MDB








On Thursday, March 21, 2024 at 07:26:22 AM CDT, dk5cr ***@***.***> wrote: 







Just tried the whole bunch of ideas on another computer, but when connecting the Xiegu x6100 to the other pc, then the same error in wsjtx 2.7.1.dev and 2.6.1 occured.
x6100_wsjtx_error.png (view on web)

**Comment by dk5cr** [comment] 2024-03-21 15:09
i tried on 9600 also with the same error on two different computers.

**Comment by mdblack98** [comment] 2024-03-21 15:14
Give me a new debug log -- it all works fine here at 19,200 which is apparently the only baud rate the X6100 supports.

Please place this file as described below
https://www.dropbox.com/s/t52ngcalsgnpm8m/wsjtx_log_config.ini?dl=0


    C:\Users\[username]\AppData\Local\WSJT-X
    The WSJT-X_Rigcontrol.log file will be in the same location
    Here's a youtube video showing Windows users howto -- https://www.youtube.com/watch?v=q9tAvhNmSvc


For Linux put it in  
    ~/.config
    The WSJT-X_Rigcontrol.log file will be here:
    ~/.local/share/WSJT-X


For MacOS put it in
    /Users/[username]/Library/Preferences
 
Restart WSJT-X and duplicate the problem.
Shut down WSJT-X


Then send me the WSJT-X_RigControl.log file
Mike W9MDB








On Thursday, March 21, 2024 at 10:10:15 AM CDT, dk5cr ***@***.***> wrote: 







i tried on 9600 also with the same error on two different computers.

**Comment by dk5cr** [comment] 2024-03-21 15:24
i resetted my com-ports and set them up again. Now the upper com-port 9 is the one, which communicates on 19200. 

The TEST CAT button gets green now, afterwards wsjtx shows the communicated QRG multiplied by 1000 or so. 

But PTT doesn't work. It lights red when activated, but x6100 doesn't do anything. 

Log in a few seconds...

**Comment by dk5cr** [comment] 2024-03-21 15:30
[240321_WSJT-X_RigControl.log](https://github.com/Hamlib/Hamlib/files/14699183/240321_WSJT-X_RigControl.log)

**Comment by dk5cr** [comment] 2024-03-22 09:33
hi, 
i downloaded FW again, flashed it to the rig, upgraded the FW inside the device and started the x6100 again. 
Connecting to wsjtx worked properly, testing CAT also, PTT works, but Frequency is a 100x to high shown in Wsjtx. 

So it's unlikely, that FW is broken. 

Another OM has also x6100 in its shag. I'm gonna let him try the same and will report. Until then i have to assume, that FW is correct, device is okay, drivers are okay, but hamlib has trouble to work with the delivered xiegu-data. 

Are you sure, that the 13. character is 0 or 1 to determine, if it's VFO A or B? 

I'm gonna try it with VFO B again and let wsjtx do the logging. ... 
And what should i say? The last digit is a "1" when i switch to VFO B. 
![hamlib_error_VFOA+B](https://github.com/Hamlib/Hamlib/assets/149412955/39bec829-692a-4e75-bb47-3cd6b776f84d)

In the log for VFO B: 
read_string_generic(): RX 13 characters, direct=1
0000    fe fe e0 a4 25 00 **01** 00 40 07 14 00 fd              ....%...@....
icom_one_transaction: frm_len=13, frm_len-1=fd, frm_len-2=00

for VFO A: 
0000    fe fe e0 a4 25 00 **00** 00 40 07 14 00 fd              ....%...@....

So i assume, that there is an additional Byte to differentiate between VFO A and B?!

Perhaps your Firmware is outdated? ;-)

Do we transfer this issue to #1527 ?

**Comment by mdblack98** [comment] 2024-03-22 12:07
fe fe e0 a4 25 01 00 10 07 14 00 fdfe fe e0 a4 25 01 00 10 07 14 00 fdWhat does your System Info say is your firmware?
I've got APP 1.1.7 and Base 1.1.6

I'm absolutely positive on the 0x25 command format and # of bytes.  It's what every Icom uses and what the Xeigu CI-V manual says it is.

0x25 0x00  VFOA
0x25 0v01  VFOB
Both followed by 5 bytes
It looks like your system is adding an extra zero so doing 0x25 0x00 0x01 instead of 0x25 0x01 for example.

It has to be the firmware or something else wrong in the rig - Hamlib can't add bytes to what it reads.
Here's your rig's response to the 0x25 commandsw

fe fe e0 a4 25 00 00 00 40 07 14 00 fd              ....***@***.***
fe fe e0 a4 25 00 01 00 40 07 14 00 fd              ....***@***.***
fe fe e0 a4 25 00 00 00 40 07 14 00 fd              ....***@***.***
fe fe e0 a4 25 00 01 00 40 07 14 00 fd

And mine
fe fe e0 a4 25 00 00 10 07 14 00 fd
fe fe e0 a4 25 01 00 10 07 14 00 fd


Mine you the VFOB command still returns VFOA so that's another Xiegu bug.
It sets VFOB correctly but reads VFOA instead.

Mike W9MDB


On Friday, March 22, 2024 at 04:33:34 AM CDT, dk5cr ***@***.***> wrote: 







hi,
i downloaded FW again, flashed it to the rig, upgraded the FW inside the device and started the x6100 again.
Connecting to wsjtx worked properly, testing CAT also, PTT works, but Frequency is a 100x to high shown in Wsjtx.

So it's unlikely, that FW is broken.

Another OM has also x6100 in its shag. I'm gonna let him try the same and will report. Until then i have to assume, that FW is correct, device is okay, drivers are okay, but hamlib has trouble to work with the delivered xiegu-data.

Are you sure, that the 13. character is 0 or 1 to determine, if it's VFO A or B?

I'm gonna try it with VFO B again and let wsjtx do the logging. ...
And what should i say? The last digit is a "1" when i switch to VFO B.
hamlib_error_VFOA+B.png (view on web)

In the log for VFO B:
read_string_generic(): RX 13 characters, direct=1
0000 fe fe e0 a4 25 00 01 00 40 07 14 00 fd ....***@***.***
icom_one_transaction: frm_len=13, frm_len-1=fd, frm_len-2=00

for VFO A:
0000 fe fe e0 a4 25 00 00 00 40 07 14 00 fd ....***@***.***

So i assume, that there is an additional Byte to differentiate between VFO A and B?!

Perhaps your Firmware is outdated? ;-)

Do we transfer this issue to #1527 ?

**Comment by dk5cr** [comment] 2024-03-22 12:23
Hello Mike, 
thanks for your reply. 
I've exact the same versions for firmware and app. 
Download is from Radioddity-website. I'm gonna try to download the one from xiegu-website, even the filesize and hash-values are the same.  I'm gonna report when install is done. 
Where did @lxe loaded his firmware? Seems to have the same issue on #1527 
Cheers and 73 
Cornel, DK5CR

**Comment by lxe** [comment] 2024-03-24 17:42
I have APP 1.1.7 and BASE 1.1.6

Will try 1.1.6. Thanks @mdblack98

**Comment by lxe** [comment] 2024-03-24 17:55
I got the following loaded which is experiencing this issue:

-  `x6100udimg-v1.1.7-230804001` downloaded from https://xiegu.eu/downloads/:

   ```
   sha1sum sdcard.img
   e7e909ab451553b85a23de3b30b84079ab692749  sdcard.img
   ```
   
Currently attempting:

 - `Xiegu_X6100_Firmware_Upgrade_20230831` from https://www.radioddity.com/blogs/all/xiegu-x6100-firmware-upgrade 
 
    ```
    sha1sum sdcard_20230831.img
    6859d77b7e8c330dbe7851cccfb589ee2db33d07  sdcard_20230831.img
    ````

**Comment by lxe** [comment] 2024-03-24 18:02
```
rigctl.exe -vvv -m 3087 -r COM3 f
Opened rig model 3087, 'X6100'
14074000
```

Looks like it's working for me now with the latest firmware downloaded from radioddity....

**Comment by lxe** [comment] 2024-03-24 18:06
I think it's working for me now with `Xiegu_X6100_Firmware_Upgrade_20230831` from radioddity

```
rigctl.exe -v -m 3087 -r COM3 f
Opened rig model 3087, 'X6100'
14074000
```

**Closed** 2024-03-24 19:57 UTC
Labels: bug, needs test
