### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by ra1nb0w** [Hamlib/Hamlib#141] opened 2019-11-14 10:17 UTC
why don't release a new version?
thanks

**Comment by N0NB** [comment] 2019-11-14 16:42
First of all, there is still work being done by Mike.  Also, I seem to recall there might be some questions about the new API/ABI.

Second, I've been quite busy in real life and have been a bit slow in keeping up.  Perhaps it's time for me to move on and let someone else do this?

**Comment by ra1nb0w** [comment] 2019-11-14 17:02
Was only a simple question from a maintainer (macports), nothing more :)
Come from user questions that from time to time ask me about support for this and that and I say that that change is in master branch a not release exist.
Maybe, we can wait an answer from Mike.

**Comment by mdblack98** [comment] 2020-01-18 05:22
Not a bug so closing

**Closed by mdblack98** 2020-01-18 05:22 UTC
